Repository nanoframework/System.Net, pull requests merged in 2024-01, with the labels that each got.

#309 Update sockets to support IPV6
  nanoFramework.System.Net/DNS.cs
  nanoFramework.System.Net/IPAddress.cs
  nanoFramework.System.Net/NetworkInformation/NetworkInterface.cs
  nanoFramework.System.Net/NetworkInformation/WirelessAPConfiguration.cs
  nanoFramework.System.Net/Properties/AssemblyInfo.cs
  nanoFramework.System.Net/SocketAddress.cs
  nanoFramework.System.Net/Sockets/NetworkStream.cs
  nanoFramework.System.Net/Sockets/Socket.cs
Labels: Type: enhancement

#310 Added `==` and `!=` operator overloads to `IpAddress`
  Tests/IPAddressTests/IPAddressTests.cs
  Tests/IPAddressTests/IPAddressTests.nfproj
  Tests/IPAddressTests/nano.runsettings
  nanoFramework.System.Net/IPAddress.cs
  nanoFramework.System.Net/Properties/AssemblyInfo.cs
Labels: Type: enhancement, Breaking-Change

#311 Fixing null checks in equality operators
  Tests/IPAddressTests/IPAddressTests.cs
  nanoFramework.System.Net/IPAddress.cs
Labels: Type: bug, Type: Unit Tests
